#if !canImport(ObjectiveC)
import XCTest

extension AnyImageTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AnyImageTests = [
        ("testCopyOnWrite", testCopyOnWrite),
        ("testSequence", testSequence),
        ("testSlice", testSlice),
        ("testSubscript", testSubscript),
        ("testSubscriptRange", testSubscriptRange),
        ("testXRange", testXRange),
        ("testYRange", testYRange),
    ]
}

extension AutoreleaseTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AutoreleaseTests = [
        ("testJPEGData", testJPEGData),
        ("testPNGData", testPNGData),
    ]
}

extension ConvolutionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ConvolutionTests = [
        ("testConvoluted", testConvoluted),
    ]
}

extension EasyImagySample {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__EasyImagySample = [
        ("testAccessToAPixel", testAccessToAPixel),
        ("testCropping", testCropping),
        ("testInitialization", testInitialization),
        ("testResizing", testResizing),
        ("testRotation", testRotation),
        ("testWithNSImage", testWithNSImage),
    ]
}

extension ExtrapolationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ExtrapolationTests = [
        ("testSubscriptRangeWithExtrapolation", testSubscriptRangeWithExtrapolation),
        ("testSubscriptWithExtrapolation", testSubscriptWithExtrapolation),
    ]
}

extension HigherOrderFunctionsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__HigherOrderFunctionsTests = [
        ("testMap", testMap),
        ("testUpdate", testUpdate),
        ("testUpdatePerformance", testUpdatePerformance),
    ]
}

extension ImageAppKitTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ImageAppKitTests = [
        ("testInitWithNSImage", testInitWithNSImage),
        ("testNsImage", testNsImage),
        ("testNsImageTiffRepresentation", testNsImageTiffRepresentation),
    ]
}

extension ImageCoreGraphicsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ImageCoreGraphicsTests = [
        ("testCGImage", testCGImage),
        ("testWithCGContext", testWithCGContext),
        ("testWithCGImage", testWithCGImage),
    ]
}

extension ImageOperatorsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ImageOperatorsTests = [
        ("testAdd", testAdd),
        ("testAddAsign", testAddAsign),
        ("testAnd", testAnd),
        ("testIsEqual", testIsEqual),
        ("testIsNotEqual", testIsNotEqual),
        ("testNegate", testNegate),
        ("testNot", testNot),
        ("testSubtractAsign", testSubtractAsign),
    ]
}

extension ImageProtocolTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ImageProtocolTests = [
        ("testInitWithPixelAt", testInitWithPixelAt),
        ("testRotated", testRotated),
        ("testSlice", testSlice),
        ("testTransposed", testTransposed),
        ("testXReversed", testXReversed),
        ("testYReversed", testYReversed),
    ]
}

extension ImageSliceTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ImageSliceTests = [
        ("testInit", testInit),
        ("testPixel", testPixel),
        ("testSequence", testSequence),
        ("testSubscriptRange", testSubscriptRange),
    ]
}

extension ImageTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ImageTests = [
        ("testCopyOnWritePerformanceOfCopy", testCopyOnWritePerformanceOfCopy),
        ("testCopyOnWritePerformanceOfUpdate", testCopyOnWritePerformanceOfUpdate),
        ("testCopyPerformance", testCopyPerformance),
        ("testData", testData),
        ("testInitNamed", testInitNamed),
        ("testInitWithImageSlice", testInitWithImageSlice),
        ("testPixel", testPixel),
        ("testSequence", testSequence),
        ("testSubscriptGet", testSubscriptGet),
        ("testSubscriptRange", testSubscriptRange),
        ("testSubscriptSet", testSubscriptSet),
        ("testWithUnsafeBufferPointer", testWithUnsafeBufferPointer),
        ("testWithUnsafeBytes", testWithUnsafeBytes),
        ("testWithUnsafeMutableBufferPointer", testWithUnsafeMutableBufferPointer),
        ("testWithUnsafeMutableBytes", testWithUnsafeMutableBytes),
    ]
}

extension InterpolationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__InterpolationTests = [
        ("testSubscriptInterpolation", testSubscriptInterpolation),
        ("testSubscriptInterpolationWithExtrapolation", testSubscriptInterpolationWithExtrapolation),
    ]
}

extension PremultipliedRGBATests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PremultipliedRGBATests = [
        ("testInit", testInit),
    ]
}

extension RGBAOperatorsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RGBAOperatorsTests = [
        ("testAdd", testAdd),
        ("testAddAsign", testAddAsign),
        ("testAnd", testAnd),
        ("testNegate", testNegate),
        ("testNot", testNot),
        ("testSubtractAsign", testSubtractAsign),
    ]
}

extension RGBATests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RGBATests = [
        ("testDescription", testDescription),
        ("testGray", testGray),
        ("testInit", testInit),
    ]
}

extension ResizingTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ResizingTests = [
        ("testResized", testResized),
    ]
}

extension RotationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RotationTests = [
        ("testRotated", testRotated),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(AnyImageTests.__allTests__AnyImageTests),
        testCase(AutoreleaseTests.__allTests__AutoreleaseTests),
        testCase(ConvolutionTests.__allTests__ConvolutionTests),
        testCase(EasyImagySample.__allTests__EasyImagySample),
        testCase(ExtrapolationTests.__allTests__ExtrapolationTests),
        testCase(HigherOrderFunctionsTests.__allTests__HigherOrderFunctionsTests),
        testCase(ImageAppKitTests.__allTests__ImageAppKitTests),
        testCase(ImageCoreGraphicsTests.__allTests__ImageCoreGraphicsTests),
        testCase(ImageOperatorsTests.__allTests__ImageOperatorsTests),
        testCase(ImageProtocolTests.__allTests__ImageProtocolTests),
        testCase(ImageSliceTests.__allTests__ImageSliceTests),
        testCase(ImageTests.__allTests__ImageTests),
        testCase(InterpolationTests.__allTests__InterpolationTests),
        testCase(PremultipliedRGBATests.__allTests__PremultipliedRGBATests),
        testCase(RGBAOperatorsTests.__allTests__RGBAOperatorsTests),
        testCase(RGBATests.__allTests__RGBATests),
        testCase(ResizingTests.__allTests__ResizingTests),
        testCase(RotationTests.__allTests__RotationTests),
    ]
}
#endif
